# .streamlit/secrets.toml

SUPABASE_URL = "https://iolijebkydqwixrllmyi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvbGlqZWJreWRxd2l4cmxsbXlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTMxOTUsImV4cCI6MjA2NjE4OTE5NX0.YS02QAFBpwQs13coG7jS3zQm9kAlRSmzAusvaobz-JQ"
